name = "cf-worker-deploy-test"
main = "./src/worker.ts"
compatibility_date = "2025-08-14"
compatibility_flags = ["durable_object_websocket"]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "WS_DO"
class_name = "WebSocketHibernationServer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketHibernationServer"]
